### ISSUE TITLE
Backend > Fix > Corrigir process.env.NODE_ENV do database config.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#15]
# OVERVIEW 
- Existe um problema no momento em que o NODE_ENV é setado no SO Windows, onde a variável, ao invés de vir como `dev` ou `start`, está vindo como `'dev'` ou `'start'`.

# TASK
- [x] Crie uma solução elegante para que essa variável seja corretamente lida tanto no Ubuntu quanto no Windows.

**Comment by FLuiz22** [comment]
https://github.com/codexjr-dev/dashboard-codex-api/pull/16
