### ISSUE TITLE
Backend > Refactor > Adicionar novos roles como disponíveis no Model de Usuário.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#19]
# OVERVIEW 
- As atuais Funções disponíveis nos campos de "Adicionar usuário" são: `Assessor(a)`, `Diretor(a)`, `Presidente` e `Conselheiro(a)`.
- Para melhor gestão de antigos membros da EJ ou para dar acesso aos Guardiões e Trainees, essas opções podem ser ampliadas com `Pós-Júnior`, `Guardiã(o)`, `Trainee` e `Ex-Trainee`.

# TASK
- [x] Atualizar as funções citadas.

**Comment by Anaritamed** [comment]
![Image](https://github.com/codexjr-dev/dashboard-codex-api/assets/100716949/17a2654a-0975-40ae-aa63-199403fd1d6f)
