### ISSUE TITLE
Backend > Refactor > Atualizar e adicionar novas opções as tags presentes nos Projetos.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#48]
# OVERVIEW 
- As atuais Tags disponíveis nos campos de "Adicionar projeto" são: `backend`, `frontend`, `wordpress`, `assessoria` e `treinamento`.
- Para deixar mais organizado e ampliar as opções, poderíamos utilizar `Backend`, `Frontend`, `Mobile`, `Wordpress`, `Assessoria` e `Treinamento`.

# TASK
- [x] Atualizar as tags citadas.

# LINKS:
- Issue of Frontend: https://github.com/codexjr-dev/dashboard-codex-web/issues/61
- Issue of Frontend in project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=37865129

**Comment by Anaritamed** [comment]
https://github.com/codexjr-dev/dashboard-codex-api/pull/50
