### ISSUE TITLE
Backend > Fix > Ao editar um membro, a função não está retornando o membro.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#52]
# OVERVIEW

- A função updateOne não retorna o objeto membro, desse modo, a resposta da requisição de atualizar o membro não está retornando o objeto esperado;
- Isso faz com que a notificação de edição de membro apareça com undefined.

# TASKS
- [x] Atualizar o retorno do updateMember para um objeto que retorne o usuário.

**Comment by Anaritamed** [comment]
https://github.com/codexjr-dev/dashboard-codex-api/pull/56
