### ISSUE TITLE
Backend > Feature > Validar o formato do e-mail ao adicionar um novo membro.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#55]
# OVERVIEW 
- Atualmente tem sido possível criar um novo membro com qualquer valor no campo de e-mail, sendo esse valor diferente de qualquer outro e-mail já registrado;
- Desse modo, valores que não correspondem ao regex ideal para o campo de e-mail estão sendo registrados e isso não deveria ser possível.

# TASK
- [x] Adicionar validação ao formato do e-mail, no service de Adicionar Membro.

**Comment by matheusvictoor** [comment]
https://github.com/codexjr-dev/dashboard-codex-api/pull/new/iss%2355

**Comment by matheusvictoor** [comment]
#55
