### ISSUE TITLE
Backend > Refactor > Limitar criação de EJ com o mesmo e-mail para uma só EJ.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#6]
# OVERVIEW 
- Um problema crucial e existente no sistema ocorre no momento de cadastro de uma EJ, onde o presidente (usuário responsável por criar a EJ, até o momento), ao clicar no botão de "Criar conta", consegue criar diversas EJs iguais, sem nem ter o conhecimento de que a primeira tentativa já foi válida.
- Para isso, é interessante implementar três soluções que restringirão a possibilidade do mesmo problema acontecer.
  1. No ambiente de Frontend, implementar uma notificação de que "A Empresa Júnior está sendo cadastrada", no momento em que o usuário clicar no botão. ([link da Issue para o Frontend presente aqui](https://github.com/codexjr-dev/dashboard-codex-web/issues/17));
  2. No ambiente de Frontend, redirecionar o usuário para a Tela de Login, após a resposta da requisição chegar. ([link da Issue para o Frontend presente aqui](https://github.com/codexjr-dev/dashboard-codex-web/issues/17));
  3. No ambiente de Backend, adicionar uma verificação para o caso de uma EJ, com aquele e-mail do presidente, já existir; Retornando, assim, uma resposta de que a EJ já foi criada com aquele e-mail.

# TASK
- [x] Adicionar uma verificação para o caso de uma EJ, com aquele e-mail do presidente, já existir; Retornando, assim, uma resposta de que a EJ já foi criada com aquele e-mail.

# Links:
- Issue of Frontend: https://github.com/codexjr-dev/dashboard-codex-web/issues/17
- Link in Frontend Project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=34193449

**Comment by Anaritamed** [comment]
https://github.com/codexjr-dev/dashboard-codex-api/pull/9
