### ISSUE TITLE
Backend > Refactor > Editar mensagem de retorno na resposta da função "remove" do Controller de Membro

### ISSUE THREAD

**Issue by Anaritamed** [codexjr-dev/projexa-api#67]
# OVERVIEW
- Atualmente, a mensagem de retorno da resposta ao remover um membro com sucesso no `MemberController` está "Membero removido com sucesso!".
- Atualizar para "Membro removido com sucesso!".

# TASK
- [x] Atualizar mensagem ao remover um membro com sucesso no MemberController;

**Comment by carlos-lucenag** [comment]
#97
