### ISSUE TITLE
Backend > Docs > Criar o arquivo COLLAB.md > Breve descrição Codex

### ISSUE THREAD

**Issue by Anaritamed** [codexjr-dev/projexa-api#79]
# OVERVIEW 
- Na ideia de aprimorar a apresentação de nosso projeto, é interessante que uma boa documentação seja escrita.
- Desse modo, para orientar futuros devs que desejam colaborar no projeto, como eles podem se engajar, crie uma breve descrição da CodexJr no arquivo `COLLAB.md` na raiz do projeto;

# TASK
- [x] Criar uma `Breve descrição da CodeX`;

# LINKS
- Link of Issue README.md: https://github.com/codexjr-dev/dashboard-codex-api/issues/59
- Link of Issue README.md in project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=38095299

**Comment by Anaritamed** [comment]
https://github.com/codexjr-dev/dashboard-codex-api/pull/76

**Comment by ManoMax** [comment]
# COMMENT

- Main Issue: https://github.com/codexjr-dev/projexa-api/issues/63
