### ISSUE TITLE
Backend > Refactor > Adicionar se já existe um usuário com o e-mail cadastrado, ao adicionar um novo usuário.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#8]
# OVERVIEW 
- Atualmente, é possível que ocorra a criação de mais de um usuário com o mesmo e-amail.

# TASK
- [x] Adicionar verificação da existência de outro usuário já cadastrado com aquele e-mail.
- [x] Impossibilitar a criação de mais de um usuário com o mesmo e-mail.

# Links:
- Issue of Frontend: https://github.com/codexjr-dev/dashboard-codex-web/issues/20
- Link in Frontend Project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=35226864

**Comment by Anaritamed** [comment]
https://github.com/codexjr-dev/dashboard-codex-api/pull/24
