### ISSUE TITLE
Backend > Docs > Criar o arquivo COLLAB.md > Tags do kanbam e criar uma Issue

### ISSUE THREAD

**Issue by FLuiz22** [codexjr-dev/projexa-api#80]
# OVERVIEW

- Na ideia de aprimorar a apresentação de nosso projeto, é interessante que uma boa documentação seja escrita.
- Desse modo, para orientar futuros devs que desejam colaborar no projeto, como eles podem se engajar, crie uma breve descrição da CodexJr no arquivo COLLAB.md na raiz do projeto;

# TASKS
- [x] Como funcionam as TAGS do Kanban
- [x] Como criar uma Issue e passa-la pra Backlog

**Comment by FLuiz22** [comment]
#76

**Comment by ManoMax** [comment]
# COMMENT

- Main Issue: https://github.com/codexjr-dev/projexa-api/issues/63
