### ISSUE TITLE
Backend > Docs > Criar o arquivo COLLAB.md > Visualização da prototipação

### ISSUE THREAD

**Issue by danieleolivs** [codexjr-dev/projexa-api#82]
# OVERVIEW

- Na ideia de aprimorar a apresentação de nosso projeto, é interessante que uma boa documentação seja escrita.
- Desse modo, para orientar futuros devs que desejam colaborar no projeto, como eles podem se engajar, crie um arquivo chamado COLLAB.md na raiz do projeto;

# TASK
- [x] Exibir a prototipação do sistema;
- [x] Contatos da CodeX Jr. (e-mail, site, Instagram e LinkedIn)

**Comment by ManoMax** [comment]
# COMMENT

- Main Issue: https://github.com/codexjr-dev/projexa-api/issues/63
