### ISSUE TITLE
Backend > Feature > Remover acesso ao sistema para membros com o Cargo "Ex-Trainee".

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-api#88]
# OVERVIEW 
- Para garantir mais segurança quanto aos dados internos da empresa, membros que passaram pelo período probatório mas decidiram não seguir atuando na empresa e não foram assinados (vulgo "Ex-Trainees") devem perder acesso.
- Desse modo, crie um "black-list" para que os usuários com esse cargo não tenham acesso ao sistema;
- Nesse caso, atribua  um array à uma variável com o nome blacklist e adicione a string `Ex-Trainee` nesse array. Caso o user.role esteja contido nesse array, deve ser retornado `USER_WITHOUT_PERMISSION`.

# TASK
- [x] Criar a variável blacklist;
- [x] Remover acesso ao sistema para membros com o Cargo `Ex-Trainee`.

**Comment by carlos-lucenag** [comment]
#96
