### ISSUE TITLE
Backend > Fix > Permitir que uma liderança edite as informações de um membro

### ISSUE THREAD

**Issue by FLuiz22** [codexjr-dev/projexa-api#94]
# OVERVIEW

- Enquanto liderança, ao tentar editar um membro, deve-se permitir a edição, porém, ao alterar qualquer dado o back retorna a mensagem "WITHOUT_PERMISSION" ao tentar salvar as alterações, ou seja, não está permitindo que uma liderança altere os dados de um membro;
- Ao invés de pegar o cargo de quem está fazendo a alteração para verificar se ele tem permissão ou não, o backend está usando de base o cargo de quem está sendo alterado, logo, não permite que uma liderança altere um membro que não seja liderança;

# TASKS

- [x] Permitir que uma liderança altere as informações de um membro;

**Comment by matheusvictoor** [comment]
#95
