### ISSUE TITLE
Backend > Feature > Criar nova rota para pegar apenas um projeto

### ISSUE THREAD

**Issue by FLuiz22** [codexjr-dev/projexa-api#98]
# OVERVIEW

- Com a criação da nova página de visualização de um único projeto, viu-se a necessidade de possuir uma rota para retornar apenas um único projeto ao invés de pegar todos e fazer uma busca;

# TASKS

- [x] Criar uma nova rota para pegar um projeto;

**Comment by ManoMax** [comment]
# COMMENT

- A função getDTOProject pode ser substituída pela função `select` da própria biblioteca mongoose.
Ficando algo como:
```js
const project = await Project.findOne({_id: projectId})
      .select('_id ej name description tags team startDate finishDate contractLink customer news')
      .populate({ path: 'team', select: 'name role _id' });
```
